### ISSUE TITLE
컨테이너 내부 로그 수집 & 호스트 전송 파이프라인

### ISSUE THREAD

**Issue by dusen0528** [Pangyo-Coffee-Legends/backlog#136]
![Image](https://github.com/user-attachments/assets/1eb2d9b0-b0f9-46bc-9ea5-aa9db5be13ff)

이렇게 도커에서 Logstash를 띄워서 파이프라인을 구성한 가장 큰 이유는 내가 원하는 이름으로 인덱스를 찍어­기 위해서 위와 같이 플로우 구성

- output { … index => "aiot2-logs-%{+YYYY.MM.dd}" } 처럼 파이프라인 설정만 바꿔서
aiot2-logs-2025.05.13
aiot2-logs-2025.05.14
… 이런 식으로 전용 인덱스로 구성 가능

## 플로우 요약 
1. Filebeat → 로컬 Logstash (컨테이너 내부 통신)

2. Logstash 파이프라인에서 index => "aiot2-logs-%{+YYYY.MM.dd}" 로 설정

3. Logstash → 원격 Elasticsearch(9200) (호스트 네트워크)

4. Kibana에서 aiot2-logs-* 패턴으로 검색

---
## docker-compose.yml
```
version: '3.8'
networks:
  elk-net:
    driver: bridge

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    container_name: aiot2-logstash
    ports:
      - "5044:5044"
    networks:
      - elk-net
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.1
    container_name: aiot2-filebeat
    user: root
    depends_on:
      - logstash
    networks:
      - elk-net
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /home/aiot2/aiot2-team2/data-processor/logs:/logs/data-processor:ro
```
