### ISSUE TITLE
filebeat 서비스 항목 추가

### ISSUE THREAD

**Issue by dusen0528** [Pangyo-Coffee-Legends/backlog#154]
## filebeat.yml
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/data-processor/app.log
    - /logs/token/app.log
    - /logs/gateway/app.log
    - /logs/meeting-room/app.log
    - /logs/token/app.log
  scan_frequency: 5s
  tail_files: false
  close_inactive: 1m

  json.keys_under_root: true
  json.add_error_key: true
  json.overwrite_keys: false

output.logstash:
  hosts: ["logstash:5044"]
```

## docker-compose.yml
```
version: '3.8'
networks:
  elk-net:
    driver: bridge

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    container_name: aiot2-logstash
    ports:
      - "5044:5044"
    networks:
      - elk-net
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.1
    container_name: aiot2-filebeat
    user: root
    depends_on:
      - logstash
    networks:
      - elk-net
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /home/aiot2/aiot2-team2/data-processor/logs:/logs/data-processor:ro
      - /home/aiot2/aiot2-team2/threshold/logs:/logs/threshold:ro
      - /home/aiot2/aiot2-team2/gateway/logs:/logs/gateway:ro
      - /home/aiot2/aiot2-team2/meeting-room/logs:/logs/meeting-room:ro
      - /home/aiot2/aiot2-team2/token/logs:/logs/token:ro
```
