### ISSUE TITLE
Config server 구성 및 가이드

### ISSUE THREAD

**Issue by dusen0528** [Pangyo-Coffee-Legends/backlog#174]
### 1. 개요

* **역할**: 중앙 설정 저장소(`config-repo`)의 YAML/Properties 파일을 읽어 각 서비스에 설정 제공
* **접근 URL**: `http://<config-server-host>:10267`

### 2. 구성 요소

1. **설정 저장소 (config-repo)**

   * GitHub: `git@github.com:Pangyo-Coffee-Legends/config-repo.git`
   * 파일 구조 예시:

     ```text
     config-repo/
     ├─ application.yml              # 공통 설정
     ├─ notify-service.yml           # notify-service 전용
     ├─ token-service.yml            # token-service 전용
     ├─ rule-engine-service.yml      # rule-engine-service 전용
     └─ front-service.yml            # front-service 전용
     ```
2. **Config-Server(Spring Cloud Config Server)**

   * Spring Boot 기반 애플리케이션
   * **Port**: `10267`
   * **Git Backend**: 위 `config-repo`

#### 3.1. `pom.xml` (의존성 및 BOM)

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-dependencies</artifactId>
      <version>2024.0.1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
<dependencies>
  <!-- Config Server -->
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-server</artifactId>
  </dependency>
  <!-- 웹 서버 & Actuator -->
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
  </dependency>
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
  </dependency>
</dependencies>
```

#### 3.2. 메인 애플리케이션 클래스

```java
@SpringBootApplication
@EnableConfigServer
public class ConfigServerApplication {
  public static void main(String[] args) {
    SpringApplication.run(ConfigServerApplication.class, args);
  }
}
```

#### 3.3. `application.properties`

```properties
spring.application.name=config-server
server.port=10267

spring.cloud.config.server.git.uri=git@github.com:Pangyo-Coffee-Legends/config-repo.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
```

### 4. CI/CD 워크플로우 (GitHub Actions)

```yaml
name: Config Server CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Prepare server directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/config-server
            rm -f ~/config-server/*.jar

      - name: Upload JAR
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: target/*.jar
          target: ~/config-server
          overwrite: true

      - name: Restart Config Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/config-server
            PID=$(lsof -ti :10267) || true
            [ -n "$PID" ] && kill -15 $PID
            nohup java -jar *.jar > logs/config-server.log 2>&1 &
```

### 5. 동작 확인

1. Config-Server-App 기동 후:

   ```bash
   curl http://localhost:10267/{서비스명}/{프로파일}
   ```

   예: `curl http://localhost:10267/notify-service/default`
2. JSON 형태로 설정이 제대로 반환되는지 확인
