### ISSUE TITLE
[공통] 서비스별 Configuration 설정하는 방법

### ISSUE THREAD

**Issue by dusen0528** [Pangyo-Coffee-Legends/backlog#177]
# 1. 의존성 추가
## 1-1. SpringCloud BOM Import
![Image](https://github.com/user-attachments/assets/9a306418-0324-4f22-ac2c-666d7fc8e0d9)
```
 <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2024.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
- repositories 위에 넣어줍니다.
- Spring Cloud 관련 라이브러리들의 호환되는 버전을 한 곳에서 관리하게 해 줍니다.

## 1-2. Config Client 의존성 추가
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
```
- ConfigServer에서 설정을 내려받기 위한 클라이언트 모듈입니다.

## 1-3. actuator 의존성 추가
- 아마 이미 들어가있을 수 있지만 한번 체크 해보시길 바랍니다
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
```

---
# 2. application.properties
기본적으로 config-repo에 각 서비스 application.yml 혹은 properties가 존재합니다.
![Image](https://github.com/user-attachments/assets/f79bcad8-2d8f-49bb-a429-68bb85315c3a)

- 기존에 저희가 하던 과정과 같이 우선 application.properties는 gitignore에 추가된 상태여야 합니다( 이렇게 하지 않을 경우 별도로 로컬에 config-repo , config-server을 내려받아 실행시킨 상태로 로컬 개발 진행해야함)
- 각 서비스의 원격 레포지토리로 가서 (src/main/resources/application.properties)를 생성합니다.

### 예시 
예: config-repo/data-processor-service.yml

```
# config-repo/data-processor-service.yml
spring:
  application:
    name: data-processor-service

server:
  port: 10262

mqtt:
  broker:
    url: tcp://115.94.72.197:1883
  client:
    id: coffee-dev-inho-test
  topic: data/#

influxdb:
  url: http://localhost:10268
  token: RmaabELI9VpYPRu4nt_xBZX5l3Gv5lx8XnR4mVZnqep4Ya3eYrfpLUk4Y4dYE4J0mlcFHFPLUCKh8a4jq_lMNw==
  org: aiot2-team2-coffee
  bucket: coffee-mqtt

model:
  api-url: http://localhost:10264/api/v1/sensor

async:
  core-pool-size: 4
  max-pool-size: 10
```

예 : 서비스의 원격 레포지토리 # src/main/resources/application.properties 
이거 복사하셔서 서비스별 application.name 변경하시면
```
spring.config.import=optional:configserver:

spring.application.name=data-processor-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
spring.cloud.config.uri=http://localhost:10267

management.endpoints.web.exposure.include=health,info,refresh,env,configprops
management.endpoint.refresh.enabled=true

```

---
# 3. 원격 서버에서 바꿔줘야 할 것들
기존 startup.sh
```
aiot2-team2@ubuntu:~/data-processor$ cat startup.sh
#!/bin/bash
PID=$(lsof -ti :10262)
if [ -n "$PID" ]; then
  kill -15 $PID
fi

cd /home/aiot2/aiot2-team2/data-processor

JAR_FILE=$(ls target/*.jar | head -n1)
if [ -z "$JAR_FILE" ]; then
  echo "JAR 파일이 없습니다!"
  exit 1
fi

nohup /usr/local/java/java21/bin/java \
  -Dserver.port=10262 \
  -Dspring.config.import=optional:file:/home/aiot2/aiot2-team2/data-processor/application.properties \
  -jar "$JAR_FILE" \
  < /dev/null > /dev/null 2>&1 &
```
변경한다면?
```
다른 설정들 ...
...
..


nohup /usr/local/java/java21/bin/java \
  -Dserver.port=서비스포트 \ 
  -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-default} \
  -Dspring.cloud.config.uri=http://localhost:10267 \
  -Dspring.config.import=optional:configserver: \
  -jar "$JAR_FILE" \
  > logs/data-processor.log 2>&1 &
```

---
# 4. 배포파일 (.github/workflows/maven.yml) 수정하기

![Image](https://github.com/user-attachments/assets/787ba5af-944e-4551-8608-3e23b732b3d8)

이 application.properties를 생성하는 부분 지워주시면 됩니다

대신 이전에 3단계인 startup.sh에 명시된 -Dspring.cloud.config.uri 옵션으로 ConfigServer 셋팅을 가져가게 됩니다.

## 이렇게 한다면 ..

- 서비스가 기동될 때 spring.cloud.config.uri 로 지정된 Config Server(localhost:10267) 에 호출

- Config Server가 config-repo/data-processor-service.properties 를 내려줘서

- 실제 설정(포트·DB 등)은 중앙 레포에서 관리되고,

- 서비스 레포에는 민감 정보가 남지 않습니다.

또한  1-3 actuator 설정을 해줬기 때문에 서비스가 구동된 상태에서
curl -X POST http://<서비스호스트>:<포트>/actuator/refresh 
만 호출하면 변경된 설정을 즉시 반영해 줍니다

예시
```
curl -X POST http://s4.java21.net:10255/actuator/refresh
```
한다면 멤버 서비스가 변경된 설정이 즉시 반영됩니다 !! 

---
