### ISSUE TITLE
[최인호] 로컬 환경 properties & Github Secret 관련 배포 꿀팁

### ISSUE THREAD

**Issue by dusen0528** [Pangyo-Coffee-Legends/backlog#96]
로컬 개발시
```
spring.application.name=data-processor-service

influxdb.org= ~~
influxdb.bucket= ~~
mqtt.broker.url= ~~
mqtt.client.id= ~~~
mqtt.topic= ~~

influxdb.url=~~
influxdb.token= ~~
```
이런식으로 설정을 할 때 보안 관련으로 GithubSecret 등록을 위해 ${influx.token} 이런식으로 추가를 하면 로컬환경에서 돌릴 때 env Loader 등.. 추가로 이것 저것 설정해줄게 많습니다.

그래서 저 같은 경우에는 application.properties에 그대로 사용하되, 
- .gitignore에 application.properties 추가
- git action secrets 에 application.properties내용 통으로 등록
하는 방법이 편하더라구요
---

이렇게 한다면 로컬은 로컬 환경대로 잘 돌아가고 푸쉬한 후 Git Actions가 동작할 때
```
      # 3. application.properties 파일 생성
      - name: Create application.properties file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            echo "${{ secrets.APPLICATION_PROPERTIES }}" > ~/data-processor/application.properties
```

이와 같은 동작을 정의하여 실제 서버 디렉토리에 똑같은 properties 파일이 생성되도록 했습니다.

이후 서버내 jar파일 실행 스크립트인 startup.sh 파일 내용에

```
nohup /usr/local/java/java21/bin/java \
  -Dserver.port= 포트 번호 \
  -Dspring.config.import=optional:file:/home/aiot2/aiot2-team2/data-processor/application.properties \
  -jar "$JAR_FILE" \
  > data-processor.log 2>&1 &
```
이러한 형식과 같이 application.properties 파일을 이용해 빌드하도록 해주었습니다.

그럼 간단히 해결 완료 !
